language: cpp
sudo: false
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
dist: focal
osx_image: xcode11

install:
  - cmake --version
  - cmake -DCMAKE_INSTALL_PREFIX=`pwd`/inst .
  - make
  - make install
script:
  - ./tests.sh
  - cd test-standalone
  - cmake -DCMAKE_PREFIX_PATH=../inst .
  - make
notifications:
  email: false
